######################################################################
# Automatically generated by qmake (2.01a) lun. mai 9 11:16:11 2011
######################################################################

TEMPLATE = app
TARGET = testWAV
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fft.h wavdata.h
SOURCES += fft.cpp main.cpp wavdata.cpp
